### ISSUE TITLE
Error installing DKMS driver

### ISSUE THREAD

**Issue by ghost** [vlasenko/hid-asus-dkms#23]
I followed the steps you provided in the Getting Started Section (https://github.com/vlasenko/hid-asus-dkms) but while after using the command ./dkms-add.sh it says:
DKMS: install completed.
modprobe: ERROR: could not insert 'hid_asus': Required key not available
Rebinding to hid-asus
sh: 1: cannot create /sys/bus/hid/drivers/hid-asus/bind: Directory nonexistent

**Comment by larixer** [comment]
@concom10 

```modprobe: ERROR: could not insert 'hid_asus': Required key not available```

You are using secure boot. You won't be able to run third-party (aka 'out of tree') kernel modules with secure boot. This is because for secure boot to work all the modules have to be signed - and given our module is third party it hasn't been signed.

If you want to use this module you'll need to disable secure boot.
